sonar.projectKey=webCrawler-app
sonar.projectName='crawler-api'
sonar.host.url=http://localhost:9000
# sonar.token=sqa_da7a7697fe6297338835173e837c1c69037b25f4
#this token is for the project named crawler-api
sonar.token=sqp_f6202555853b1f65f349d2be0468d4bb2fdc73d7
# sonar.login=admin
# sonar.password=!Amthes0naradmin
#Another project naming and setting
#sonar.projectKey=webCrawler-service
#sonar.projectName='crawler-api'
#sonar.host.url=http://localhost:9000
#sonar.token=sqa_da7a7697fe6297338835173e837c1c69037b25f4